// Generated by CoffeeScript 1.4.0
(function() {
  var ACCESSOR, CoffeeScript, Module, REPLServer, REPL_PROMPT, REPL_PROMPT_CONTINUATION, REPL_PROMPT_MULTILINE, SIMPLEVAR, Script, autocomplete, completeAttribute, completeVariable, enableColours, error, getCompletions, inspect, readline, stdin, stdout,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  stdin = process.openStdin();

  stdout = process.stdout;

  CoffeeScript = require('./coffee-script');

  readline = require('readline');

  inspect = require('util').inspect;

  Script = require('vm').Script;

  Module = require('module');

  REPL_PROMPT = 'coffee> ';

  REPL_PROMPT_MULTILINE = '------> ';

  REPL_PROMPT_CONTINUATION = '......> ';

  enableColours = false;

  if (process.platform !== 'win32') {
    enableColours = !process.env.NODE_DISABLE_COLORS;
  }

  error = function(err) {
    return stdout.write((err.stack || err.toString()) + '\n');
  };

  ACCESSOR = /\s*([\w\.]+)(?:\.(\w*))$/;

  SIMPLEVAR = /(\w+)$/i;

  autocomplete = function(text) {
    return completeAttribute(text) || completeVariable(text) || [[], text];
  };

  completeAttribute = function(text) {
    var all, candidates, completions, key, match, obj, prefix, _i, _len, _ref;
    if (match = text.match(ACCESSOR)) {
      all = match[0], obj = match[1], prefix = match[2];
      try {
        obj = Script.runInThisContext(obj);
      } catch (e) {
        return;
      }
      if (obj == null) {
        return;
      }
      obj = Object(obj);
      candidates = Object.getOwnPropertyNames(obj);
      while (obj = Object.getPrototypeOf(obj)) {
        _ref = Object.getOwnPropertyNames(obj);
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          key = _ref[_i];
          if (__indexOf.call(candidates, key) < 0) {
            candidates.push(key);
          }
        }
      }
      completions = getCompletions(prefix, candidates);
      return [completions, prefix];
    }
  };

  completeVariable = function(text) {
    var candidates, completions, free, key, keywords, r, vars, _i, _len, _ref;
    free = (_ref = text.match(SIMPLEVAR)) != null ? _ref[1] : void 0;
    if (text === "") {
      free = "";
    }
    if (free != null) {
      vars = Script.runInThisContext('Object.getOwnPropertyNames(Object(this))');
      keywords = (function() {
        var _i, _len, _ref1, _results;
        _ref1 = CoffeeScript.RESERVED;
        _results = [];
        for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
          r = _ref1[_i];
          if (r.slice(0, 2) !== '__') {
            _results.push(r);
          }
        }
        return _results;
      })();
      candidates = vars;
      for (_i = 0, _len = keywords.length; _i < _len; _i++) {
        key = keywords[_i];
        if (__indexOf.call(candidates, key) < 0) {
          candidates.push(key);
        }
      }
      completions = getCompletions(free, candidates);
      return [completions, free];
    }
  };

  getCompletions = function(prefix, candidates) {
    var el, _i, _len, _results;
    _results = [];
    for (_i = 0, _len = candidates.length; _i < _len; _i++) {
      el = candidates[_i];
      if (0 === el.indexOf(prefix)) {
        _results.push(el);
      }
    }
    return _results;
  };

  process.on('uncaughtException', error);

  REPLServer = (function() {

    function REPLServer(options) {
      var backlog, multilineMode,
        _this = this;
      if (options == null) {
        options = {};
      }
      multilineMode = false;
      backlog = '';
      this["eval"] = options["eval"] || function(code) {
        return CoffeeScript["eval"]("_=(" + code + "\n)", {
          filename: 'repl',
          modulename: 'repl'
        });
      };
      if (stdin.readable && stdin.isRaw) {
        this.rli = this.createPipedInterface(stdin);
      } else {
        this.rli = this.createReadlineInterface();
      }
      this.rli.input.on('keypress', function(char, key) {
        var cursorPos, newPrompt;
        if (!(key && key.ctrl && !key.meta && !key.shift && key.name === 'v')) {
          return;
        }
        cursorPos = _this.rli.cursor;
        _this.rli.output.cursorTo(0);
        _this.rli.output.clearLine(1);
        multilineMode = !multilineMode;
        if (!multilineMode && backlog) {
          _this.rli._line();
        }
        backlog = '';
        _this.rli.setPrompt((newPrompt = multilineMode ? REPL_PROMPT_MULTILINE : REPL_PROMPT));
        _this.rli.prompt();
        return _this.rli.output.cursorTo(newPrompt.length + (_this.rli.cursor = cursorPos));
      });
      this.rli.input.on('keypress', function(char, key) {
        if (!(multilineMode && _this.rli.line)) {
          return;
        }
        if (!(key && key.ctrl && !key.meta && !key.shift && key.name === 'd')) {
          return;
        }
        multilineMode = false;
        return _this.rli._line();
      });
      this.rli.on('attemptClose', function() {
        if (multilineMode) {
          multilineMode = false;
          _this.rli.output.cursorTo(0);
          _this.rli.output.clearLine(1);
          _this.rli._onLine(_this.rli.line);
          return;
        }
        if (backlog || _this.rli.line) {
          backlog = '';
          _this.rli.historyIndex = -1;
          _this.rli.setPrompt(REPL_PROMPT);
          _this.rli.output.write('\n(^C again to quit)');
          return _this.rli._line((_this.rli.line = ''));
        } else {
          return _this.rli.close();
        }
      });
      this.rli.on('close', function() {
        _this.rli.output.write('\n');
        return _this.rli.input.destroy();
      });
      this.rli.on('line', function(buffer) {
        var code, returnValue, _;
        buffer = buffer.replace(/(^|[\r\n]+)(\s*)##?(?:[^#\r\n][^\r\n]*|)($|[\r\n])/, "$1$2$3");
        buffer = buffer.replace(/[\r\n]+$/, "");
        if (multilineMode) {
          backlog += "" + buffer + "\n";
          _this.rli.setPrompt(REPL_PROMPT_CONTINUATION);
          _this.rli.prompt();
          return;
        }
        if (!buffer.toString().trim() && !backlog) {
          _this.rli.prompt();
          return;
        }
        code = backlog += buffer;
        if (code[code.length - 1] === '\\') {
          backlog = "" + backlog.slice(0, -1) + "\n";
          _this.rli.setPrompt(REPL_PROMPT_CONTINUATION);
          _this.rli.prompt();
          return;
        }
        _this.rli.setPrompt(REPL_PROMPT);
        backlog = '';
        try {
          _ = global._;
          returnValue = _this["eval"](code);
          if (returnValue === void 0) {
            global._ = _;
          }
          _this.rli.output.write("" + (inspect(returnValue, false, 2, enableColours)) + "\n");
        } catch (err) {
          error(err);
        }
        return _this.rli.prompt();
      });
    }

    REPLServer.prototype.start = function() {
      this.rli.setPrompt(REPL_PROMPT);
      return this.rli.prompt();
    };

    REPLServer.prototype.createPipedInterface = function(stdin) {
      var piped, pipedInput,
        _this = this;
      pipedInput = '';
      piped = {
        prompt: function() {
          return stdout.write(this._prompt);
        },
        setPrompt: function(p) {
          return this._prompt = p;
        },
        input: stdin,
        output: stdout,
        on: function() {}
      };
      stdin.on('data', function(chunk) {
        var line, lines, _i, _len, _ref;
        pipedInput += chunk;
        if (!/\n/.test(pipedInput)) {
          return;
        }
        lines = pipedInput.split("\n");
        pipedInput = lines[lines.length - 1];
        _ref = lines.slice(0, -1);
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          line = _ref[_i];
          if (!(line)) {
            continue;
          }
          stdout.write("" + line + "\n");
          _this.run(line);
        }
      });
      stdin.on('end', function() {
        var line, _i, _len, _ref;
        _ref = pipedInput.trim().split("\n");
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          line = _ref[_i];
          if (!(line)) {
            continue;
          }
          stdout.write("" + line + "\n");
          _this.run(line);
        }
        stdout.write('\n');
        return process.exit(0);
      });
      return piped;
    };

    REPLServer.prototype.createReadlineInterface = function() {
      var rli;
      if (readline.createInterface.length < 3) {
        rli = readline.createInterface(stdin, autocomplete);
        stdin.on('data', function(buffer) {
          return rli.write(buffer);
        });
      } else {
        rli = readline.createInterface(stdin, stdout, autocomplete);
      }
      return rli;
    };

    return REPLServer;

  })();

  new REPLServer().start();

}).call(this);
